In [16]:
import numpy as np

In [17]:
arr = np.array([1,2,3,4,5])

In [18]:
result=  arr ** 2  #Vectorized Operation using Batch Concept (SIMD)
print(result)

[ 1  4  9 16 25]


In [22]:
result + 10

array([11, 14, 19, 26, 35])

In [26]:
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([5,5,5])

result = arr1+arr2
print(result)

[[15 25 35]
 [45 55 65]]


In [27]:
np.mean(arr)

np.float64(3.0)

In [28]:
np.std(arr)

np.float64(1.4142135623730951)

In [32]:
np.max(arr)

np.int64(5)

In [33]:
np.min(arr)


np.int64(1)

In [34]:
np.prod(arr)

np.int64(120)

In [35]:
np.median(arr)

np.float64(3.0)

In [37]:
np.percentile(arr, 60)  # For the 50th percentile (median)

np.float64(3.4)

In [38]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [39]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])