In [3]:
import numpy as np

In [4]:
arr = np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [5]:
b =arr[3:7]
b    # so here b is not sub part of arr it is itself original array means that if 
     # we will chnage inside b that means that we will be directly effect on original array that as below given code 

array([40, 50, 60])

In [6]:
b[0] = 4

In [7]:
print(arr)

[10 20 30  4 50 60]


In [8]:
arr[arr>30] # boolean masking 

array([50, 60])

In [10]:
print(arr.dtype)

int64


In [13]:
arr.astype("float64")

array([10., 20., 30.,  4., 50., 60.])

In [15]:
arr.nbytes

48