In [1]:
a=[10,20,30]
b=[1,2,3]
print(a+b)

[10, 20, 30, 1, 2, 3]


In [3]:
result =[]
for i in range(3):
    result.append(a[i]+b[i])
print(result)

[11, 22, 33]


In [4]:
import numpy as np


In [5]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)

[11 22 33]


In [7]:
arr= np.array([10,2.5,3]) # convert int to float
print(arr)
print(arr.dtype)

[10.   2.5  3. ]
float64


In [9]:
arr= np.array([10,2.5,3])
arr1=np.array([1,2.5,3])
print(arr+arr1)

[11.  5.  6.]


In [11]:
arr_int =np.array([10,20,30,40,50])
arr_float = np.array([1.5,2.3,3.8,1.2])
arr_mixed = np.array([10,2.5,"Krish",True])
print(arr_int)
print(arr_float)
print(arr_mixed)

[10 20 30 40 50]
[1.5 2.3 3.8 1.2]
['10' '2.5' 'Krish' 'True']


In [13]:
a= np.array([10,20,30,40,50])
b=np.array([1,2,3,4,6])
print("Add",a+b)
print("Sub",a-b)
print("Mul",a*b)
print("div",a/b)
print("Mean",np.mean[a])
print("Mean",np.mean[b])


Add [11 22 33 44 56]
Sub [ 9 18 27 36 44]
Mul [ 10  40  90 160 300]
div [10.         10.         10.         10.          8.33333333]


TypeError: 'numpy._ArrayFunctionDispatcher' object is not subscriptable

In [14]:
import pandas as pd


In [15]:
data = [1,2,3,4,5]
ser = pd.Series(data)
print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [17]:
data =[1,2,3,4,5]
ser =pd.Series(data)
print(ser)
print(type(ser))
print(ser.index)
print(ser.values)


0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [19]:
days=['mon','tue','wed','thu','fri']
temps =np.array([30,2,31,29,21])

s =pd.Series(temps,index=days)
print(s)

mon    30
tue     2
wed    31
thu    29
fri    21
dtype: int64


In [20]:
print(s[0])
print(s[1:4])


30
tue     2
wed    31
thu    29
dtype: int64


C:\Users\krish\AppData\Local\Temp\ipykernel_28120\1316413854.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [22]:
s.head()


mon    30
tue     2
wed    31
thu    29
fri    21
dtype: int64

In [23]:
s.tail()

mon    30
tue     2
wed    31
thu    29
fri    21
dtype: int64

In [25]:
print(s.describe())

count     5.000000
mean     22.600000
std      12.177849
min       2.000000
25%      21.000000
50%      29.000000
75%      30.000000
max      31.000000
dtype: float64
